server:
  servlet:
    context-path: /credit-card-provider
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher